function result = run_sandbox_deviation_check_impl()
projectRoot = find_project_root();
resultsDir = fullfile(projectRoot, 'sandbox', 'results');
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

caseData = synthetic_fault_cases('sandbox');
caseResults = repmat(empty_sandbox_result(), 1, numel(caseData));
for i = 1:numel(caseData)
    observation = build_fault_observation(caseData(i));
    spso = run_spso_ga_optimizer(observation, spso_ga_options('SPSO-GA', 20265000 + i));
    row = empty_sandbox_result();
    row.name = observation.name;
    row.true_fault_section = observation.true_fault_section;
    row.predicted_fault_section = spso.predicted_fault_section;
    row.section_error = spso.section_error;
    row.correct = spso.correct;
    row.sensor_mode = observation.sensor_mode;
    row.flip_count = observation.flip_count;
    row.weight = observation.weight;
    caseResults(i) = row;
end

trueSections = [caseResults.true_fault_section];
predictedSections = [caseResults.predicted_fault_section];
weights = [caseResults.weight];
metrics = fault_location_metrics(trueSections, predictedSections, weights);
[worstError, worstIdx] = max([caseResults.section_error]);

result = struct();
result.data_type = 'synthetic_reproduction';
result.cases = caseResults;
result.metrics.spso_ga = metrics;
result.summary.spso_ga_accuracy_percent = metrics.accuracy_percent;
result.summary.weighted_accuracy_percent = metrics.weighted_accuracy_percent;
result.summary.worst_case = caseResults(worstIdx).name;
result.summary.worst_section_error = worstError;
result.report_path = fullfile(resultsDir, 'sandbox_deviation_report.md');
result.mat_path = fullfile(resultsDir, 'sandbox_deviation_result.mat');
result.note = 'Synthetic deviation sandbox; not original article FTU data.';

save(result.mat_path, 'result');
write_sandbox_report(result);

fprintf('Sandbox deviation report written to: %s\n', result.report_path);
fprintf('SPSO-GA accuracy: %.1f%%\n', result.summary.spso_ga_accuracy_percent);
fprintf('Worst case: %s\n', result.summary.worst_case);
end

function write_sandbox_report(result)
fid = fopen(result.report_path, 'w');
if fid == -1
    error('Cannot open sandbox report for writing: %s', result.report_path);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '# SPSO-GA Sandbox Deviation Report\n\n');
fprintf(fid, 'Generated by `run_sandbox_deviation_check.m`.\n\n');
fprintf(fid, '## Purpose\n');
fprintf(fid, 'This sandbox checks SPSO-GA under synthetic FTU deviations: alarm flips, missing FTUs, sparse terminal sensors, and difficult section 32 cases. These are not article raw data.\n\n');
fprintf(fid, '## Summary\n');
fprintf(fid, '- Cases: `%d`\n', numel(result.cases));
fprintf(fid, '- Accuracy: `%.1f%%`\n', result.summary.spso_ga_accuracy_percent);
fprintf(fid, '- Weighted accuracy: `%.1f%%`\n', result.summary.weighted_accuracy_percent);
fprintf(fid, '- Worst case: `%s`, section error `%d`\n\n', result.summary.worst_case, result.summary.worst_section_error);

fprintf(fid, '## Cases\n');
fprintf(fid, '| Case | True section | SPSO-GA section | Error | Correct | Sensor mode | Flips |\n');
fprintf(fid, '|---|---:|---:|---:|---|---|---:|\n');
for i = 1:numel(result.cases)
    row = result.cases(i);
    fprintf(fid, '| %s | %d | %d | %d | %d | %s | %d |\n', ...
        row.name, row.true_fault_section, row.predicted_fault_section, row.section_error, row.correct, row.sensor_mode, row.flip_count);
end
end

function row = empty_sandbox_result()
row = struct( ...
    'name', '', ...
    'true_fault_section', NaN, ...
    'predicted_fault_section', NaN, ...
    'section_error', NaN, ...
    'correct', false, ...
    'sensor_mode', '', ...
    'flip_count', NaN, ...
    'weight', NaN);
end

function projectRoot = find_project_root()
currentDir = fileparts(mfilename('fullpath'));
projectRoot = currentDir;
while ~isfile(fullfile(projectRoot, 'main.m'))
    parentDir = fileparts(projectRoot);
    if strcmp(parentDir, projectRoot)
        error('Project root with main.m was not found.');
    end
    projectRoot = parentDir;
end
end
