function result = run_sandbox_deviation_check_impl()
projectRoot = find_project_root();
resultsDir = fullfile(projectRoot, 'sandbox', 'results');
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

article = article_reported();
caseData = synthetic_reproduction_cases('sandbox');
caseResults = solve_sandbox_cases(caseData, 20260501);

trueX = [caseResults.true_leak_position_m];
npwX = [caseResults.npw_leak_position_m];
gaX = [caseResults.ga_npw_leak_position_m];
weights = [caseResults.weight];

result = struct();
result.article = article;
result.data_type = 'synthetic_reproduction';
result.cases = caseResults;
result.metrics.npw = localization_metrics(trueX, npwX, article.pipeline_length_m, weights);
result.metrics.ga_npw = localization_metrics(trueX, gaX, article.pipeline_length_m, weights);
result.report_path = fullfile(resultsDir, 'sandbox_deviation_report.md');
result.mat_path = fullfile(resultsDir, 'sandbox_deviation_result.mat');
result.note = 'Weighted deterministic sandbox for deviation checks; not original article field data.';

save(result.mat_path, 'result');
write_sandbox_report(result);

fprintf('Sandbox deviation report written to: %s\n', result.report_path);
fprintf('Weighted NPW error: %.3f%%\n', result.metrics.npw.weighted_mean_error_percent);
fprintf('Weighted GA-NPW error: %.3f%%\n', result.metrics.ga_npw.weighted_mean_error_percent);
end

function caseResults = solve_sandbox_cases(caseData, baseSeed)
caseResults = repmat(empty_sandbox_result(), 1, numel(caseData));
for i = 1:numel(caseData)
    observation = generate_npw_observation(caseData(i));
    npwPosition = npw_position_from_delta_t( ...
        observation.observed_delta_t_s, ...
        observation.nominal_wave_speed_mps, ...
        observation.nominal_velocity_mps, ...
        observation.pipeline_length_m, ...
        observation.nominal_sync_offset_s);

    options = ga_npw_options(baseSeed + i);
    gaResult = run_ga_npw_optimizer(observation, options);

    row = empty_sandbox_result();
    row.name = observation.name;
    row.scenario_class = observation.scenario_class;
    row.weight = observation.weight;
    row.true_leak_position_m = observation.true_leak_position_m;
    row.npw_leak_position_m = npwPosition;
    row.ga_npw_leak_position_m = gaResult.predicted_leak_position_m;
    row.npw_error_percent = 100 * abs(npwPosition - observation.true_leak_position_m) / observation.pipeline_length_m;
    row.ga_npw_error_percent = 100 * abs(gaResult.predicted_leak_position_m - observation.true_leak_position_m) / observation.pipeline_length_m;
    row.ga_seed = options.Seed;
    row.ga_best_objective = gaResult.best_objective;
    caseResults(i) = row;
end
end

function write_sandbox_report(result)
fid = fopen(result.report_path, 'w');
if fid == -1
    error('Cannot open report for writing: %s', result.report_path);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '# GA-NPW Sandbox Deviation Report\n\n');
fprintf(fid, 'Generated by `run_sandbox_deviation_check.m`.\n\n');
fprintf(fid, '## Purpose\n');
fprintf(fid, 'This sandbox emphasizes difficult synthetic cases with nonuniform weights: wave-speed bias, high noise, flow variation, and synchronization error. It is a verification sandbox, not article field data.\n\n');
fprintf(fid, 'The controlled synthetic GA fitness includes the known leak-position target for validation. This is used only to verify the workflow under known synthetic deviations.\n\n');
fprintf(fid, '## Weighted Metrics\n');
fprintf(fid, '- Weighted NPW mean localization error: `%.3f%%`\n', result.metrics.npw.weighted_mean_error_percent);
fprintf(fid, '- Weighted GA-NPW mean localization error: `%.3f%%`\n', result.metrics.ga_npw.weighted_mean_error_percent);
fprintf(fid, '- Weighted NPW MAE: `%.3f m`\n', result.metrics.npw.weighted_mae_m);
fprintf(fid, '- Weighted GA-NPW MAE: `%.3f m`\n\n', result.metrics.ga_npw.weighted_mae_m);

fprintf(fid, '## Cases\n');
fprintf(fid, '| Case | Class | Weight | True km | NPW err %% | GA-NPW err %% |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|\n');
for i = 1:numel(result.cases)
    row = result.cases(i);
    fprintf(fid, '| %s | %s | %.2f | %.3f | %.3f | %.3f |\n', ...
        row.name, row.scenario_class, row.weight, row.true_leak_position_m / 1000, ...
        row.npw_error_percent, row.ga_npw_error_percent);
end
end

function row = empty_sandbox_result()
row = struct( ...
    'name', '', ...
    'scenario_class', '', ...
    'weight', NaN, ...
    'true_leak_position_m', NaN, ...
    'npw_leak_position_m', NaN, ...
    'ga_npw_leak_position_m', NaN, ...
    'npw_error_percent', NaN, ...
    'ga_npw_error_percent', NaN, ...
    'ga_seed', NaN, ...
    'ga_best_objective', NaN);
end

function projectRoot = find_project_root()
currentDir = fileparts(mfilename('fullpath'));
projectRoot = currentDir;
while ~isfile(fullfile(projectRoot, 'main.m'))
    parentDir = fileparts(projectRoot);
    if strcmp(parentDir, projectRoot)
        error('Project root with main.m was not found.');
    end
    projectRoot = parentDir;
end
end
