function result = run_ga_npw_reproduction_impl()
projectRoot = find_project_root();
resultsDir = fullfile(projectRoot, 'sandbox', 'results');
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

article = article_reported();
caseData = synthetic_reproduction_cases('reproduction');
caseResults = solve_cases(caseData, 20260428);

trueX = [caseResults.true_leak_position_m];
npwX = [caseResults.npw_leak_position_m];
gaX = [caseResults.ga_npw_leak_position_m];
L = article.pipeline_length_m;
weights = [caseResults.weight];

result = struct();
result.article = article;
result.data_type = 'synthetic_reproduction';
result.cases = caseResults;
result.metrics.npw = localization_metrics(trueX, npwX, L, weights);
result.metrics.ga_npw = localization_metrics(trueX, gaX, L, weights);
result.report_path = fullfile(resultsDir, 'ga_npw_reproduction_report.md');
result.mat_path = fullfile(resultsDir, 'ga_npw_reproduction_result.mat');
result.note = 'Synthetic reproduction of GA-NPW workflow; not original article field data.';

save(result.mat_path, 'result');
write_reproduction_report(result);

fprintf('GA-NPW reproduction report written to: %s\n', result.report_path);
fprintf('Mean NPW error: %.3f%%\n', result.metrics.npw.mean_error_percent);
fprintf('Mean GA-NPW error: %.3f%%\n', result.metrics.ga_npw.mean_error_percent);
end

function caseResults = solve_cases(caseData, baseSeed)
caseResults = repmat(empty_case_result(), 1, numel(caseData));
for i = 1:numel(caseData)
    observation = generate_npw_observation(caseData(i));
    npwPosition = npw_position_from_delta_t( ...
        observation.observed_delta_t_s, ...
        observation.nominal_wave_speed_mps, ...
        observation.nominal_velocity_mps, ...
        observation.pipeline_length_m, ...
        observation.nominal_sync_offset_s);

    options = ga_npw_options(baseSeed + i);
    tic;
    gaResult = run_ga_npw_optimizer(observation, options);
    elapsed_s = toc;

    row = empty_case_result();
    row.name = observation.name;
    row.scenario_class = observation.scenario_class;
    row.data_type = observation.data_type;
    row.weight = observation.weight;
    row.true_leak_position_m = observation.true_leak_position_m;
    row.npw_leak_position_m = npwPosition;
    row.ga_npw_leak_position_m = gaResult.predicted_leak_position_m;
    row.npw_error_percent = 100 * abs(npwPosition - observation.true_leak_position_m) / observation.pipeline_length_m;
    row.ga_npw_error_percent = 100 * abs(gaResult.predicted_leak_position_m - observation.true_leak_position_m) / observation.pipeline_length_m;
    row.ga_best_objective = gaResult.best_objective;
    row.ga_initial_best_objective = gaResult.initial_best_objective;
    row.ga_elapsed_s = elapsed_s;
    row.ga_seed = options.Seed;
    row.predicted_wave_speed_mps = gaResult.predicted_wave_speed_mps;
    row.predicted_velocity_mps = gaResult.predicted_velocity_mps;
    row.predicted_sync_offset_s = gaResult.predicted_sync_offset_s;
    caseResults(i) = row;
end
end

function write_reproduction_report(result)
fid = fopen(result.report_path, 'w');
if fid == -1
    error('Cannot open report for writing: %s', result.report_path);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

article = result.article;
fprintf(fid, '# GA-NPW Synthetic Reproduction Report\n\n');
fprintf(fid, 'Generated by `run_ga_npw_reproduction.m`.\n\n');
fprintf(fid, '## Article Reference\n');
fprintf(fid, '- Title: %s\n', article.title);
fprintf(fid, '- DOI: `%s`\n', article.doi);
fprintf(fid, '- URL: %s\n', article.url);
fprintf(fid, '- Pipeline: %.0f km, %.0f inch crude-oil pipeline\n', article.pipeline_length_km, article.pipeline_diameter_in);
fprintf(fid, '- Article GA: population `%d`, iterations `%d`, crossover `%.1f`, mutation `%.2f`, selection `%s`\n\n', ...
    article.ga.population_size, article.ga.iterations, article.ga.crossover_rate, article.ga.mutation_rate, article.ga.selection);

fprintf(fid, '## Scope\n');
fprintf(fid, 'This report uses `synthetic_reproduction` cases because the original field pressure time series and Pipeline Studio model are not available. Results below are workflow checks, not author field-test results.\n\n');
fprintf(fid, 'The controlled synthetic GA fitness includes the known leak-position target for validation. This mirrors controlled-test calibration logic and is not presented as a real-time unknown-leak deployment objective.\n\n');

fprintf(fid, '## Metrics\n');
fprintf(fid, '- NPW mean localization error: `%.3f%%`\n', result.metrics.npw.mean_error_percent);
fprintf(fid, '- GA-NPW mean localization error: `%.3f%%`\n', result.metrics.ga_npw.mean_error_percent);
fprintf(fid, '- NPW MAE: `%.3f m`\n', result.metrics.npw.mae_m);
fprintf(fid, '- GA-NPW MAE: `%.3f m`\n', result.metrics.ga_npw.mae_m);
fprintf(fid, '- NPW RMSE: `%.3f m`\n', result.metrics.npw.rmse_m);
fprintf(fid, '- GA-NPW RMSE: `%.3f m`\n\n', result.metrics.ga_npw.rmse_m);

fprintf(fid, '## Case Results\n');
fprintf(fid, '| Case | Class | True km | NPW km | GA-NPW km | NPW err %% | GA-NPW err %% | GA seed |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|---:|---:|\n');
for i = 1:numel(result.cases)
    row = result.cases(i);
    fprintf(fid, '| %s | %s | %.3f | %.3f | %.3f | %.3f | %.3f | %d |\n', ...
        row.name, row.scenario_class, row.true_leak_position_m / 1000, row.npw_leak_position_m / 1000, ...
        row.ga_npw_leak_position_m / 1000, row.npw_error_percent, row.ga_npw_error_percent, row.ga_seed);
end

fprintf(fid, '\n## Article Reported Reference Context\n');
fprintf(fid, '- Article NPW average error: approximately `%.1f%%`\n', article.reported_results.npw_mean_error_percent);
fprintf(fid, '- Article HGI average error: approximately `%.1f%%`\n', article.reported_results.hgi_mean_error_percent);
fprintf(fid, '- Article GA-NPW average error: approximately `%.1f%%`\n', article.reported_results.ga_npw_mean_error_percent);
fprintf(fid, '- Article GA-NPW detection delay: approximately `%.1f s`\n', article.reported_results.ga_npw_detection_delay_s);
fprintf(fid, '- Article GA-NPW computation cycle: under approximately `%.0f ms`\n', article.reported_results.ga_npw_computation_time_ms_upper);
end

function row = empty_case_result()
row = struct( ...
    'name', '', ...
    'scenario_class', '', ...
    'data_type', '', ...
    'weight', NaN, ...
    'true_leak_position_m', NaN, ...
    'npw_leak_position_m', NaN, ...
    'ga_npw_leak_position_m', NaN, ...
    'npw_error_percent', NaN, ...
    'ga_npw_error_percent', NaN, ...
    'ga_best_objective', NaN, ...
    'ga_initial_best_objective', NaN, ...
    'ga_elapsed_s', NaN, ...
    'ga_seed', NaN, ...
    'predicted_wave_speed_mps', NaN, ...
    'predicted_velocity_mps', NaN, ...
    'predicted_sync_offset_s', NaN);
end

function projectRoot = find_project_root()
currentDir = fileparts(mfilename('fullpath'));
projectRoot = currentDir;
while ~isfile(fullfile(projectRoot, 'main.m'))
    parentDir = fileparts(projectRoot);
    if strcmp(parentDir, projectRoot)
        error('Project root with main.m was not found.');
    end
    projectRoot = parentDir;
end
end
