function result = run_sandbox_deviation_check_impl()
projectRoot = find_project_root();
resultsDir = fullfile(projectRoot, 'sandbox', 'results');
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

caseData = synthetic_source_cases('sandbox');
caseResults = repmat(empty_case_result(), 1, numel(caseData));

for i = 1:numel(caseData)
    observation = build_synthetic_observation(caseData(i));
    options = nmga_options('NMGA', 'quick', 20265000 + i);
    runResult = run_nmga_optimizer(observation, options, options.NMGA500Generations);
    caseResults(i) = summarize_case(caseData(i), runResult);
end

positionErrors = [caseResults.position_error_m];
[worstPositionError, worstIdx] = max(positionErrors);

result = struct();
result.data_type = 'synthetic_reproduction';
result.cases = caseResults;
result.summary.baseline_position_error_m = caseResults(1).position_error_m;
result.summary.mean_position_error_m = mean(positionErrors);
result.summary.worst_position_error_m = worstPositionError;
result.summary.worst_case = caseResults(worstIdx).name;
result.report_path = fullfile(resultsDir, 'sandbox_deviation_report.md');
result.mat_path = fullfile(resultsDir, 'sandbox_deviation_result.mat');
result.note = 'Synthetic sandbox for source inversion deviations; not article monitoring data.';

save(result.mat_path, 'result');
write_sandbox_report(result);

fprintf('Sandbox deviation report written to: %s\n', result.report_path);
fprintf('Mean position error: %.3f m\n', result.summary.mean_position_error_m);
fprintf('Worst position error: %.3f m (%s)\n', result.summary.worst_position_error_m, result.summary.worst_case);
end

function row = summarize_case(caseData, runResult)
row = empty_case_result();
row.name = caseData.name;
row.layout = caseData.layout;
row.noise_fraction = caseData.noise_fraction;
row.weight = caseData.weight;
row.true_source = [caseData.true_x_m, caseData.true_y_m, caseData.true_Q_gps, caseData.true_H_m];
row.estimated_source = runResult.best_x;
row.position_error_m = runResult.metrics.position_error_m;
row.Q_relative_error_percent = runResult.metrics.Q_relative_error_percent;
row.H_relative_error_percent = runResult.metrics.H_relative_error_percent;
row.best_objective = runResult.best_objective;
row.seed = runResult.options.Seed;
end

function write_sandbox_report(result)
fid = fopen(result.report_path, 'w');
if fid == -1
    error('Cannot open sandbox report for writing: %s', result.report_path);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '# NMGA Sandbox Deviation Report\n\n');
fprintf(fid, 'Generated by `run_sandbox_deviation_check.m`.\n\n');
fprintf(fid, '## Purpose\n');
fprintf(fid, 'This sandbox stress-checks NMGA source inversion under synthetic deviations: concentration noise, fewer sensors, biased wind speed, shifted source location, and high/low source intensity. These are not article field data.\n\n');
fprintf(fid, '## Summary\n');
fprintf(fid, '- Cases: `%d`\n', numel(result.cases));
fprintf(fid, '- Mean position error: `%.3f m`\n', result.summary.mean_position_error_m);
fprintf(fid, '- Worst position error: `%.3f m` in `%s`\n\n', result.summary.worst_position_error_m, result.summary.worst_case);

fprintf(fid, '## Cases\n');
fprintf(fid, '| Case | Layout | Noise | True x | True y | Est x | Est y | Position err m | Q rel err %% | H rel err %% |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|---:|---:|---:|---:|\n');
for i = 1:numel(result.cases)
    row = result.cases(i);
    fprintf(fid, '| %s | %s | %.3f | %.2f | %.2f | %.2f | %.2f | %.3f | %.3f | %.3f |\n', ...
        row.name, row.layout, row.noise_fraction, row.true_source(1), row.true_source(2), ...
        row.estimated_source(1), row.estimated_source(2), row.position_error_m, ...
        row.Q_relative_error_percent, row.H_relative_error_percent);
end
end

function row = empty_case_result()
row = struct( ...
    'name', '', ...
    'layout', '', ...
    'noise_fraction', NaN, ...
    'weight', NaN, ...
    'true_source', [NaN, NaN, NaN, NaN], ...
    'estimated_source', [NaN, NaN, NaN, NaN], ...
    'position_error_m', NaN, ...
    'Q_relative_error_percent', NaN, ...
    'H_relative_error_percent', NaN, ...
    'best_objective', NaN, ...
    'seed', NaN);
end

function projectRoot = find_project_root()
currentDir = fileparts(mfilename('fullpath'));
projectRoot = currentDir;
while ~isfile(fullfile(projectRoot, 'main.m'))
    parentDir = fileparts(projectRoot);
    if strcmp(parentDir, projectRoot)
        error('Project root with main.m was not found.');
    end
    projectRoot = parentDir;
end
end
