function result = run_nmga_reproduction_impl(profile)
if nargin < 1 || isempty(profile)
    profile = 'quick';
end

projectRoot = find_project_root();
resultsDir = fullfile(projectRoot, 'sandbox', 'results');
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

article = article_reported();
caseData = synthetic_source_cases('reproduction');
observation = build_synthetic_observation(caseData);
baseOptions = nmga_options('NMGA', profile, 20260428);

mgaRuns = repmat(empty_run_result(), 1, baseOptions.RepeatCount);
nmga1000Runs = repmat(empty_run_result(), 1, baseOptions.RepeatCount);
nmga500Runs = repmat(empty_run_result(), 1, baseOptions.RepeatCount);

for i = 1:baseOptions.RepeatCount
    mgaOptions = nmga_options('MGA', profile, 20260428 + i);
    nmga1000Options = nmga_options('NMGA', profile, 20261428 + i);
    nmga500Options = nmga_options('NMGA', profile, 20262428 + i);

    mgaRuns(i) = summarize_run(run_mga_optimizer(observation, mgaOptions));
    nmga1000Runs(i) = summarize_run(run_nmga_optimizer(observation, nmga1000Options, nmga1000Options.NMGA1000Generations));
    nmga500Runs(i) = summarize_run(run_nmga_optimizer(observation, nmga500Options, nmga500Options.NMGA500Generations));
end

result = struct();
result.article = article;
result.profile = profile;
result.repeat_count = baseOptions.RepeatCount;
result.data_type = 'synthetic_reproduction';
result.observation = observation;
result.runs.mga = mgaRuns;
result.runs.nmga_1000 = nmga1000Runs;
result.runs.nmga_500 = nmga500Runs;
result.metrics.mga = aggregate_runs(mgaRuns);
result.metrics.nmga_1000 = aggregate_runs(nmga1000Runs);
result.metrics.nmga_500 = aggregate_runs(nmga500Runs);
result.report_path = fullfile(resultsDir, 'nmga_reproduction_report.md');
result.mat_path = fullfile(resultsDir, 'nmga_reproduction_result.mat');
result.note = 'Synthetic reproduction of the article workflow; not original article monitoring data.';

save(result.mat_path, 'result');
write_reproduction_report(result);

fprintf('NMGA reproduction report written to: %s\n', result.report_path);
fprintf('MGA mean position error: %.3f m\n', result.metrics.mga.mean_position_error_m);
fprintf('NMGA-500 mean position error: %.3f m\n', result.metrics.nmga_500.mean_position_error_m);
end

function row = summarize_run(runResult)
row = empty_run_result();
row.method = runResult.method;
row.generations = runResult.generations;
row.seed = runResult.options.Seed;
row.best_objective = runResult.best_objective;
row.initial_best_objective = runResult.initial_best_objective;
row.best_x = runResult.best_x;
row.position_error_m = runResult.metrics.position_error_m;
row.Q_relative_error_percent = runResult.metrics.Q_relative_error_percent;
row.H_relative_error_percent = runResult.metrics.H_relative_error_percent;
end

function aggregate = aggregate_runs(runs)
aggregate = struct();
aggregate.count = numel(runs);
aggregate.mean_position_error_m = mean([runs.position_error_m]);
aggregate.std_position_error_m = std([runs.position_error_m]);
aggregate.mean_Q_relative_error_percent = mean([runs.Q_relative_error_percent]);
aggregate.mean_H_relative_error_percent = mean([runs.H_relative_error_percent]);
aggregate.mean_best_objective = mean([runs.best_objective]);
aggregate.mean_initial_objective = mean([runs.initial_best_objective]);
aggregate.mean_x_m = mean(arrayfun(@(r) r.best_x(1), runs));
aggregate.mean_y_m = mean(arrayfun(@(r) r.best_x(2), runs));
aggregate.mean_Q_gps = mean(arrayfun(@(r) r.best_x(3), runs));
aggregate.mean_H_m = mean(arrayfun(@(r) r.best_x(4), runs));
end

function write_reproduction_report(result)
fid = fopen(result.report_path, 'w');
if fid == -1
    error('Cannot open report for writing: %s', result.report_path);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

article = result.article;
fprintf(fid, '# NMGA Synthetic Reproduction Report\n\n');
fprintf(fid, 'Generated by `run_nmga_reproduction.m` with profile `%s`.\n\n', result.profile);
fprintf(fid, '## Article Reference\n');
fprintf(fid, '- Title: %s\n', article.title);
fprintf(fid, '- DOI: `%s`\n', article.doi);
fprintf(fid, '- URL: %s\n', article.url);
fprintf(fid, '- Article scenario: Q `%.2f g/s`, Hr `%.2f m`, wind `%.2f m/s`, stability `%s`, target near (`%.2f`, `%.2f`).\n\n', ...
    article.scenario.Q_gps, article.scenario.Hr_m, article.scenario.wind_speed_mps, article.scenario.stability, ...
    article.scenario.target_x_m, article.scenario.target_y_m);

fprintf(fid, '## Scope\n');
fprintf(fid, 'This report uses `synthetic_reproduction` observations because exact monitoring data and figure-eight coordinates are not available in this workspace. Results are workflow checks, not article raw-data reproduction.\n\n');

fprintf(fid, '## Synthetic Metrics\n');
fprintf(fid, '| Method | Repeats | Mean x | Mean y | Mean Q | Mean H | Mean position error m | Mean Q rel err %% | Mean H rel err %% |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|---:|---:|\n');
write_metric_row(fid, 'MGA quick/2000-aligned', result.metrics.mga);
write_metric_row(fid, 'NMGA quick/1000-aligned', result.metrics.nmga_1000);
write_metric_row(fid, 'NMGA quick/500-aligned', result.metrics.nmga_500);

fprintf(fid, '\n## Article Table 1 Values Encoded For Comparison\n');
fprintf(fid, '| Method | Setup | Mean x | Mean y | Mean Q | Mean Hr |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|\n');
for i = 1:numel(article.table1)
    row = article.table1(i);
    fprintf(fid, '| %s | %s | %.4f | %.4f | %.2f | %.4f |\n', ...
        row.method, row.setup, row.mean_x_m, row.mean_y_m, row.mean_Q_gps, row.mean_Hr_m);
end

fprintf(fid, '\n## Limitation\n');
fprintf(fid, 'The article states that data sharing is not applicable. This package reproduces the modeling and optimizer workflow on synthetic observations and does not claim exact duplication of Table 1 raw calculations.\n');
end

function write_metric_row(fid, label, metrics)
fprintf(fid, '| %s | %d | %.4f | %.4f | %.2f | %.4f | %.3f | %.3f | %.3f |\n', ...
    label, metrics.count, metrics.mean_x_m, metrics.mean_y_m, metrics.mean_Q_gps, metrics.mean_H_m, ...
    metrics.mean_position_error_m, metrics.mean_Q_relative_error_percent, metrics.mean_H_relative_error_percent);
end

function row = empty_run_result()
row = struct( ...
    'method', '', ...
    'generations', NaN, ...
    'seed', NaN, ...
    'best_objective', NaN, ...
    'initial_best_objective', NaN, ...
    'best_x', [NaN, NaN, NaN, NaN], ...
    'position_error_m', NaN, ...
    'Q_relative_error_percent', NaN, ...
    'H_relative_error_percent', NaN);
end

function projectRoot = find_project_root()
currentDir = fileparts(mfilename('fullpath'));
projectRoot = currentDir;
while ~isfile(fullfile(projectRoot, 'main.m'))
    parentDir = fileparts(projectRoot);
    if strcmp(parentDir, projectRoot)
        error('Project root with main.m was not found.');
    end
    projectRoot = parentDir;
end
end
