function profile = pc_profile()
%PC_PROFILE Audited execution profile for the user's Dell G3 3579.

profile = struct( ...
    "auditDate", "2026-07-30", ...
    "cpu", "Intel Core i5-8300H", ...
    "physicalCores", 4, ...
    "logicalProcessors", 8, ...
    "installedRAMGiB", 31.86, ...
    "freeRAMGiBAtAudit", 19.97, ...
    "matlabRelease", "R2026a Update 4", ...
    "parallelWorkerLimit", 4, ...
    "recommendedWorkers", 4, ...
    "interactiveWorkers", 3, ...
    "recommendedPool", "Processes", ...
    "gpuAvailableToMATLAB", false, ...
    "gpuReason", "parallel:gpu:device:OldDriver", ...
    "systemDriveFreeGiB", 13.04, ...
    "workspaceOnOneDrive", true, ...
    "processBenchmarkSerialSeconds", 4.231843, ...
    "processBenchmarkFourWorkersSeconds", 1.805608, ...
    "processBenchmarkFourWorkerSpeedup", 2.343723, ...
    "threadBenchmarkFourWorkersSeconds", 1.995641, ...
    "threadBenchmarkFourWorkerSpeedup", 2.120543);
end
