function eu2617_validate_config(cfg)
%EU2617_VALIDATE_CONFIG Fail-closed validation for the clean-room harness.

required = { ...
    'v_min', 'v_max', ...
    'mutation_rate_min', 'mutation_rate_max', ...
    'mutation_rate_multiplier', ...
    'crossover_rate_min', 'crossover_rate_max', ...
    'crossover_rate_multiplier'};
for index = 1:numel(required)
    name = required{index};
    if ~isfield(cfg, name) || ~isnumeric(cfg.(name)) ...
            || ~isscalar(cfg.(name)) || ~isfinite(cfg.(name))
        error('eu2617:BadConfig', '%s must be a finite numeric scalar', name);
    end
end

if cfg.v_min < 0 || cfg.v_min >= cfg.v_max
    error('eu2617:BadConfig', 'thresholds must satisfy 0 <= v_min < v_max');
end
if cfg.mutation_rate_min < 0 ...
        || cfg.mutation_rate_min > cfg.mutation_rate_max ...
        || cfg.mutation_rate_max > 1
    error('eu2617:BadConfig', 'mutation-rate bounds must lie in [0, 1] in order');
end
if cfg.crossover_rate_min < 0 ...
        || cfg.crossover_rate_min > cfg.crossover_rate_max ...
        || cfg.crossover_rate_max > 1
    error('eu2617:BadConfig', 'crossover-rate bounds must lie in [0, 1] in order');
end
if cfg.mutation_rate_multiplier <= 1 ...
        || cfg.crossover_rate_multiplier <= 1
    error('eu2617:BadConfig', 'rate multipliers must be greater than one');
end
end
