function report = verify_project_structure(projectRoot)
if nargin < 1 || isempty(projectRoot)
    projectRoot = find_project_root();
end

required = { ...
    'README.md', ...
    'main.m', ...
    'run_article_exact_reproduction.m', ...
    'run_nmga_reproduction.m', ...
    'run_nmga_adaptive_audit.m', ...
    'run_sandbox_deviation_check.m', ...
    'run_unit_tests.m', ...
    fullfile('docs', 'article-summary.md'), ...
    fullfile('docs', 'project-notes.md'), ...
    fullfile('docs', 'verification-guide.md'), ...
    fullfile('src', 'data', 'article_exact_spec.m'), ...
    fullfile('src', 'data', 'article_reported.m'), ...
    fullfile('src', 'data', 'synthetic_sensor_grid.m'), ...
    fullfile('src', 'data', 'synthetic_source_cases.m'), ...
    fullfile('src', 'models', 'gaussian_plume_concentration.m'), ...
    fullfile('src', 'models', 'pasquill_gifford_e.m'), ...
    fullfile('src', 'models', 'source_objective.m'), ...
    fullfile('src', 'optimization', 'nmga_options.m'), ...
    fullfile('src', 'optimization', 'nmga_adaptive_rates.m'), ...
    fullfile('src', 'optimization', 'article_egp_crossover.m'), ...
    fullfile('src', 'optimization', 'article_gene_pool_split.m'), ...
    fullfile('src', 'optimization', 'article_nonuniform_delta.m'), ...
    fullfile('src', 'optimization', 'article_operator_probe.m'), ...
    fullfile('src', 'optimization', 'run_mga_optimizer.m'), ...
    fullfile('src', 'optimization', 'run_nmga_optimizer.m'), ...
    fullfile('src', 'optimization', 'run_nmga_adaptive_audit_impl.m'), ...
    fullfile('src', 'optimization', 'run_article_exact_reproduction_impl.m'), ...
    fullfile('src', 'optimization', 'run_nmga_reproduction_impl.m'), ...
    fullfile('src', 'optimization', 'run_sandbox_deviation_check_impl.m'), ...
    fullfile('src', 'metrics', 'source_estimation_metrics.m'), ...
    fullfile('tests', 'run_unit_tests_impl.m')};

checks = repmat(struct('path', '', 'exists', false), 1, numel(required));
failures = {};
for i = 1:numel(required)
    checks(i).path = required{i};
    checks(i).exists = isfile(fullfile(projectRoot, required{i}));
    if ~checks(i).exists
        failures{end + 1} = required{i}; %#ok<AGROW>
    end
end

report = struct();
report.checks = checks;
report.failures = failures;
report.pass_count = sum([checks.exists]);
report.fail_count = numel(required) - report.pass_count;
report.passed = report.fail_count == 0;
end

function projectRoot = find_project_root()
currentDir = fileparts(mfilename('fullpath'));
projectRoot = currentDir;
while ~isfile(fullfile(projectRoot, 'main.m'))
    parentDir = fileparts(projectRoot);
    if strcmp(parentDir, projectRoot)
        error('Project root with main.m was not found.');
    end
    projectRoot = parentDir;
end
end
