function report = verify_project_structure(projectRoot)
if nargin < 1 || isempty(projectRoot)
    projectRoot = find_project_root();
end

required = { ...
    'README.md', ...
    'main.m', ...
    'run_spso_ga_reproduction.m', ...
    'run_sandbox_deviation_check.m', ...
    'run_unit_tests.m', ...
    fullfile('article', 'source-reference.md'), ...
    fullfile('docs', 'article-summary.md'), ...
    fullfile('docs', 'project-notes.md'), ...
    fullfile('docs', 'verification-guide.md'), ...
    fullfile('src', 'data', 'article_reported.m'), ...
    fullfile('src', 'data', 'ieee33_synthetic_network.m'), ...
    fullfile('src', 'data', 'synthetic_fault_cases.m'), ...
    fullfile('src', 'models', 'downstream_nodes.m'), ...
    fullfile('src', 'models', 'fault_signature.m'), ...
    fullfile('src', 'models', 'build_fault_observation.m'), ...
    fullfile('src', 'models', 'fault_objective.m'), ...
    fullfile('src', 'optimization', 'spso_ga_options.m'), ...
    fullfile('src', 'optimization', 'run_spso_ga_optimizer.m'), ...
    fullfile('src', 'optimization', 'run_spso_ga_reproduction_impl.m'), ...
    fullfile('src', 'optimization', 'run_sandbox_deviation_check_impl.m'), ...
    fullfile('src', 'metrics', 'fault_location_metrics.m'), ...
    fullfile('tests', 'run_unit_tests_impl.m')};

checks = repmat(struct('path', '', 'exists', false), 1, numel(required));
failures = {};
for i = 1:numel(required)
    checks(i).path = required{i};
    checks(i).exists = isfile(fullfile(projectRoot, required{i}));
    if ~checks(i).exists
        failures{end + 1} = required{i}; %#ok<AGROW>
    end
end

report = struct();
report.checks = checks;
report.failures = failures;
report.pass_count = sum([checks.exists]);
report.fail_count = numel(required) - report.pass_count;
report.passed = report.fail_count == 0;
end

function projectRoot = find_project_root()
currentDir = fileparts(mfilename('fullpath'));
projectRoot = currentDir;
while ~isfile(fullfile(projectRoot, 'main.m'))
    parentDir = fileparts(projectRoot);
    if strcmp(parentDir, projectRoot)
        error('Project root with main.m was not found.');
    end
    projectRoot = parentDir;
end
end
