function result = run_spso_ga_reproduction_impl()
projectRoot = find_project_root();
resultsDir = fullfile(projectRoot, 'sandbox', 'results');
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

article = article_reported();
caseData = synthetic_fault_cases('reproduction');
caseResults = solve_cases(caseData, 20260428);

trueSections = [caseResults.true_fault_section];
psoSections = [caseResults.pso_ga_prediction];
spsoSections = [caseResults.spso_ga_prediction];
weights = [caseResults.weight];

result = struct();
result.article = article;
result.data_type = 'synthetic_reproduction';
result.cases = caseResults;
result.metrics.pso_ga = fault_location_metrics(trueSections, psoSections, weights);
result.metrics.spso_ga = fault_location_metrics(trueSections, spsoSections, weights);
result.report_path = fullfile(resultsDir, 'spso_ga_reproduction_report.md');
result.mat_path = fullfile(resultsDir, 'spso_ga_reproduction_result.mat');
result.note = 'Synthetic reproduction of SPSO-GA workflow; not original article FTU data.';

save(result.mat_path, 'result');
write_reproduction_report(result);

fprintf('SPSO-GA reproduction report written to: %s\n', result.report_path);
fprintf('PSO-GA accuracy: %.1f%%\n', result.metrics.pso_ga.accuracy_percent);
fprintf('SPSO-GA accuracy: %.1f%%\n', result.metrics.spso_ga.accuracy_percent);
end

function caseResults = solve_cases(caseData, baseSeed)
caseResults = repmat(empty_case_result(), 1, numel(caseData));
for i = 1:numel(caseData)
    observation = build_fault_observation(caseData(i));
    pso = run_spso_ga_optimizer(observation, spso_ga_options('PSO-GA', baseSeed + i));
    spso = run_spso_ga_optimizer(observation, spso_ga_options('SPSO-GA', baseSeed + 1000 + i));

    row = empty_case_result();
    row.name = observation.name;
    row.true_fault_section = observation.true_fault_section;
    row.sensor_mode = observation.sensor_mode;
    row.flip_count = observation.flip_count;
    row.weight = observation.weight;
    row.pso_ga_prediction = pso.predicted_fault_section;
    row.spso_ga_prediction = spso.predicted_fault_section;
    row.pso_ga_correct = pso.correct;
    row.spso_ga_correct = spso.correct;
    row.pso_ga_section_error = pso.section_error;
    row.spso_ga_section_error = spso.section_error;
    caseResults(i) = row;
end
end

function write_reproduction_report(result)
fid = fopen(result.report_path, 'w');
if fid == -1
    error('Cannot open report for writing: %s', result.report_path);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

article = result.article;
fprintf(fid, '# SPSO-GA Synthetic Reproduction Report\n\n');
fprintf(fid, 'Generated by `run_spso_ga_reproduction.m`.\n\n');
fprintf(fid, '## Article Reference\n');
fprintf(fid, '- Title: %s\n', article.title);
fprintf(fid, '- DOI: `%s`\n', article.doi);
fprintf(fid, '- URL: %s\n', article.url);
fprintf(fid, '- Network: %s, %d nodes, %d sections\n', article.network.name, article.network.node_count, article.network.section_count);
fprintf(fid, '- Article settings: N `%d`, iterations `%d`, repeated tests `%d`\n', article.algorithm.population_size, article.algorithm.iterations, article.algorithm.repeated_tests);
fprintf(fid, '- PSO-GA: omega `%.1f`, c1 `%.1f`, c2 `%.1f`\n', article.algorithm.pso_ga.omega, article.algorithm.pso_ga.c1, article.algorithm.pso_ga.c2);
fprintf(fid, '- SPSO-GA: omega `%.1f`, c1 `%.1f`, c2 `%.1f`\n\n', article.algorithm.spso_ga.omega, article.algorithm.spso_ga.c1, article.algorithm.spso_ga.c2);

fprintf(fid, '## Scope\n');
fprintf(fid, 'This report uses `synthetic_reproduction` FTU signatures because original FTU upload data and simulation tables are not available in this workspace.\n\n');

fprintf(fid, '## Metrics\n');
fprintf(fid, '- PSO-GA accuracy: `%.1f%%`\n', result.metrics.pso_ga.accuracy_percent);
fprintf(fid, '- SPSO-GA accuracy: `%.1f%%`\n', result.metrics.spso_ga.accuracy_percent);
fprintf(fid, '- PSO-GA mean section error: `%.3f`\n', result.metrics.pso_ga.mean_section_error);
fprintf(fid, '- SPSO-GA mean section error: `%.3f`\n\n', result.metrics.spso_ga.mean_section_error);

fprintf(fid, '## Cases\n');
fprintf(fid, '| Case | True section | PSO-GA | SPSO-GA | Sensor mode | Flips |\n');
fprintf(fid, '|---|---:|---:|---:|---|---:|\n');
for i = 1:numel(result.cases)
    row = result.cases(i);
    fprintf(fid, '| %s | %d | %d | %d | %s | %d |\n', row.name, row.true_fault_section, row.pso_ga_prediction, row.spso_ga_prediction, row.sensor_mode, row.flip_count);
end

fprintf(fid, '\n## Limitation\n');
fprintf(fid, 'The report validates the workflow and objective implementation on synthetic cases. It does not claim exact reproduction of the authors raw FTU data.\n');
end

function row = empty_case_result()
row = struct( ...
    'name', '', ...
    'true_fault_section', NaN, ...
    'sensor_mode', '', ...
    'flip_count', NaN, ...
    'weight', NaN, ...
    'pso_ga_prediction', NaN, ...
    'spso_ga_prediction', NaN, ...
    'pso_ga_correct', false, ...
    'spso_ga_correct', false, ...
    'pso_ga_section_error', NaN, ...
    'spso_ga_section_error', NaN);
end

function projectRoot = find_project_root()
currentDir = fileparts(mfilename('fullpath'));
projectRoot = currentDir;
while ~isfile(fullfile(projectRoot, 'main.m'))
    parentDir = fileparts(projectRoot);
    if strcmp(parentDir, projectRoot)
        error('Project root with main.m was not found.');
    end
    projectRoot = parentDir;
end
end
